SET hive.vectorized.execution.enabled=false;
SET hive.vectorized.execution.reduce.enabled=false;

--EJECUTA EL BORRADO DE LA TABLA TEMPORAL AL INICIO
DROP TABLE IF EXISTS db_desarrollo2021.otc_t_catalogo_consolidado_id;

--CREA TABLA TEMPORAL CON LA INFORMACION DEL REPORTE CIPF AUXILIAR
CREATE EXTERNAL TABLE db_desarrollo2021.otc_t_catalogo_consolidado_id(
descripcion string,
codigo string,
nombre_id string,
extractor string
)
COMMENT 'Tabla que contiene el catalogo unificado para proyecto comisiones'
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY '|'
STORED AS TEXTFILE
LOCATION '/DataExternal/db_desarrollo2021/otc_t_catalogo_consolidado_id'
tblproperties ("skip.header.line.count"="1");



--insertado en RF
,EQUIPO_ALTA, ICC_ALTA
,COD_CATEGORIA
,DOMAIN_LOGIN_OW_ALTA, NOMBRE_USUARIO_OW_ALTA
,DOMAIN_LOGIN_SUB_ALTA, NOMBRE_USUARIO_SUB_ALTA
,A.COD_DA, NOM_USUARIO
,CAMPANIA_ALTA, CODIGO_DISTRIBUIDOR_ALTA
,CODIGO_PLAZA_ALTA,  NOM_PLAZA_ALTA,  REGION_ALTA
,PROVINCIA_IVR
,EJECUTIVO_ASIGNADO_PTR_ALTA, AREA_PTR_ALTA
,CODIGO_VENDEDOR_DA_PTR_ALTA,  JEFATURA_PTR_ALTA
,PROVINCIA_MS
,CODIGO_USUARIO_ALTA
,CALF_RIESGO_ALTA, CAP_ENDEU_ALTA, VALOR_CRED_ALTA

---XXXXXXXXXXXXXXXXXXXXXXXXXX-------
-----------------INSERTADO EN RF
,FECHA_NR,
CANAL_COMERCIAL_NR,
CAMPANIA_NR,
CODIGO_DISTRIBUIDOR_NR,
DISTRIBUIDOR_NR,
CODIGO_PLAZA_NR, 
NOM_PLAZA_NR, 
REGION_NR,
----------XXXXXXXXXXXXX
-- LOS CAMPOS ENTRE XXXXXXX SE OBTIENEN CRUZANDO CON EL CAT DE USUARIOS
LINEA_NEGOCIO_BAJA,
DOCUMENTO_CLIENTE_ANT,
DIAS,
FECHA_BAJA
---XXXXXXXXXXXXXXXXX----------------------------------------------------------------
--INSERTADO EN RF
--C.IMEI AS IMEI_TI, 
,EQUIPO_TI, ICC_TI,
DOMAIN_LOGIN_OW_TI, NOMBRE_USUARIO_OW_TI,
DOMAIN_LOGIN_SUB_TI, CODIGO_DISTRIBUIDOR_TI,
CODIGO_PLAZA_TI,  NOM_PLAZA_TI, REGION_TI,
EJECUTIVO_ASIGNADO_PTR_TI, AREA_PTR_TI, 
CODIGO_VENDEDOR_DA_PTR_TI,  JEFATURA_PTR_TI,
CODIGO_USUARIO_TI,
CALF_RIESGO_TI, CAP_ENDEU_TI, VALOR_CRED_TI,
ACCOUNT_NUM_ANTERIOR_TI, CIUDAD_USUARIO_TI, 
PROVINCIA_USUARIO_TI, MISMO_CLIENTE_TI,
--------------------------------------------
--INSERTADO EN RF
--D.IMEI AS IMEI_TO, 
EQUIPO_TO, ICC_TO,
DOMAIN_LOGIN_OW_TO, NOMBRE_USUARIO_OW_TO,
DOMAIN_LOGIN_SUB_TO, NOMBRE_USUARIO_SUB_TO,
CAMPANIA_TO, CODIGO_DISTRIBUIDOR_TO,
CODIGO_PLAZA_TO, NOM_PLAZA_TO, REGION_TO,
EJECUTIVO_ASIGNADO_PTR_TO, AREA_PTR_TO, 
CODIGO_VENDEDOR_DA_PTR_TO, JEFATURA_PTR_TO,
CODIGO_USUARIO_TO,
CALF_RIESGO_TO, CAP_ENDEU_TO, VALOR_CRED_TO,
ACCOUNT_NUM_ANTERIOR_TO, CIUDAD_USUARIO_TO, 
PROVINCIA_USUARIO_TO, MISMO_CLIENTE_TO
--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

--INSERTADO EN RF
DOMAIN_LOGIN_OW_CP, NOMBRE_USUARIO_OW_CP,
DOMAIN_LOGIN_SUB_CP, NOMBRE_USUARIO_SUB_CP,
CAMPANIA_CP, CODIGO_DISTRIBUIDOR_CP,
CODIGO_PLAZA_CP, NOM_PLAZA_CP, REGION_CP,
NOMBRE_PLAN_ANTERIOR, TARIFA_BASICA_ANTERIOR,
FECHA_INICIO_PLAN_ANTERIOR,
TARIFA_FINAL_PLAN_ACT, TARIFA_FINAL_PLAN_ANT
-------------XXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------