--HQL REFACTORING 360_MOVIMIENTOS_PARQUE

--OTC_T_NO_RECICLABLES_HIST

set hive.cli.print.header=false;	
set hive.vectorized.execution.enabled=false;
set hive.vectorized.execution.reduce.enabled=false;
set tez.queue.name=${VAL_COLA_EJECUCION}; --SE CAMBIO EN RF
	
	
--------------------------------------INSERTADO EN RF-PARA INCLUIR TABLA NO RECLICLABLES------------------------------------
--ELIMINA LA DATA PRE EXISTENTE
DELETE FROM ${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST WHERE TIPO='NO_RECICLABLE' AND FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}';
	--IF EXISTS 
--INSERTA LA DATA DEL MES
INSERT INTO ${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST
SELECT 'NO_RECICLABLE' AS TIPO, 
NUM_TELEFONICO AS TELEFONO,
FECHA_ALTA, 
DOCUMENTO_CLIENTE_ACT,
PLAN_CODIGO,
FECHA_PROCESO,
CAST( NULL AS STRING) as CANAL_COMERCIAL,
CAST( NULL AS STRING) as CAMPANIA,
CAST( NULL AS STRING) as CODIGO_DISTRIBUIDOR,
CAST( NULL AS STRING) as DISTRIBUIDOR,
CAST( NULL AS STRING) as CODIGO_PLAZA, 
CAST( NULL AS STRING) as NOM_PLAZA, 
CAST( NULL AS STRING) as REGION,
MARCA,
LINEA_NEGOCIO_BAJA,
DOCUMENTO_CLIENTE_ANT,
DIAS,
FECHA_BAJA
----------------------------------------------MODIFICAR FORMATO FECHA YYYY-MM-DD
FROM db_cs_altas.no_reciclable WHERE FECHA_PROCESO='${fecha_proceso}' and marca ='TELEFONICA';	
----------------------------------------------xxxxxxxxxxxxxxxxxxxxxxxxx-------------------------------------------------------



--ELIMINA LA DATA PRE EXISTENTE
DELETE FROM ${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST WHERE TIPO='ALTA' AND FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}'  ;
	--IF EXISTS 
--INSERTA LA DATA DEL MES
INSERT INTO ${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST
SELECT 'ALTA' AS TIPO , TELEFONO,
FECHA_ALTA AS FECHA, 
CANAL_COMERCIAL AS CANAL,
SUB_CANAL, 
CAST( NULL AS STRING) as NUEVO_SUB_CANAL,
PORTABILIDAD, 
Operadora_origen,
'MOVISTAR (OTECEL)' as Operadora_destino,
CAST( NULL AS STRING) as motivo,		   
NOM_DISTRIBUIDOR as DISTRIBUIDOR,
OFICINA,
--INSERTADO EN RF
IMEI, EQUIPO, ICC,
COD_CATEGORIA,
DOMAIN_LOGIN_OW, NOMBRE_USUARIO_OW,
DOMAIN_LOGIN_SUB, NOMBRE_USUARIO_SUB,
COD_DA, NOM_USUARIO,
CAMPANIA, CODIGO_DISTRIBUIDOR,
CODIGO_PLAZA, NOM_PLAZA, REGION, 
PROVINCIA_IVR,
EJECUTIVO_ASIGNADO_PTR, AREA_PTR, 
CODIGO_VENDEDOR_DA_PTR, JEFATURA_PTR,
PROVINCIA_MS,
CODIGO_USUARIO,
CALF_RIESGO, CAP_ENDEU, VALOR_CRED
	  
FROM db_cs_altas.otc_t_altas_bi WHERE p_FECHA_PROCESO='${fecha_movimientos_cp}' and marca ='TELEFONICA';--es particionada

--ELIMINA LA DATA PRE EXISTENTE
DELETE FROM ${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST WHERE TIPO='BAJA' AND FECHA  BETWEEN '${f_inicio}' AND '${fecha_proceso}';
	--IF EXISTS 
--INSERTA LA DATA DEL MES
INSERT INTO ${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST
SELECT 'BAJA' AS TIPO ,TELEFONO,
FECHA_BAJA AS FECHA, 
CAST( NULL AS STRING) AS CANAL,
CAST( NULL AS STRING) AS SUB_CANAL, 
CAST( NULL AS STRING) as NUEVO_SUB_CANAL,
PORTABILIDAD, 
'MOVISTAR (OTECEL)' AS  Operadora_origen,
Operadora_destino,
MOTIVO_BAJA as motivo,
CAST( NULL AS STRING) as DISTRIBUIDOR , 
CAST( NULL AS STRING) AS OFICINA,

--INSERTADO EN RF
CAST( NULL AS STRING) AS IMEI, CAST( NULL AS STRING) AS EQUIPO, CAST( NULL AS STRING) AS ICC,
CAST( NULL AS STRING) AS COD_CATEGORIA,
CAST( NULL AS STRING) AS DOMAIN_LOGIN_OW, CAST( NULL AS STRING) AS NOMBRE_USUARIO_OW,
CAST( NULL AS STRING) AS DOMAIN_LOGIN_SUB, CAST( NULL AS STRING) AS NOMBRE_USUARIO_SUB,
CAST( NULL AS STRING) AS COD_DA, CAST( NULL AS STRING) AS NOM_USUARIO,
CAST( NULL AS STRING) AS CAMPANIA, CAST( NULL AS STRING) AS CODIGO_DISTRIBUIDOR,
CAST( NULL AS STRING) AS CODIGO_PLAZA, CAST( NULL AS STRING) AS NOM_PLAZA, CAST( NULL AS STRING) AS REGION, 
CAST( NULL AS STRING) AS PROVINCIA_IVR,
EJECUTIVO_ASIGNADO_PTR, AREA_PTR, 
CODIGO_VENDEDOR_DA_PTR, JEFATURA_PTR,
CAST( NULL AS STRING) AS PROVINCIA_MS,
CAST( NULL AS STRING) AS CODIGO_USUARIO,
CAST( NULL AS STRING) AS CALF_RIESGO, CAST( NULL AS STRING) AS CAP_ENDEU, CAST( NULL AS STRING) AS VALOR_CRED
---------------------------------------
FROM db_cs_altas.otc_t_BAJAS_bi WHERE p_FECHA_PROCESO='${fecha_movimientos_cp}' and marca ='TELEFONICA';

--ELIMINA LA DATA PRE EXISTENTE DEL MES QUE SE PROCESA
DELETE FROM ${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST WHERE TIPO='PRE_POS' AND FECHA  BETWEEN '${f_inicio}' AND '${fecha_proceso}'  ;
	--IF EXISTS 
--INSERTA LA DATA DEL MES
INSERT INTO ${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST
SELECT 'PRE_POS' AS TIPO,
TELEFONO,
FECHA_TRANSFERENCIA AS FECHA, 
CANAL_USUARIO as CANAL,
SUB_CANAL, 
CAST( NULL AS STRING) AS NUEVO_SUB_CANAL,         
NOM_DISTRIBUIDOR_USUARIO AS DISTRIBUIDOR, 
OFICINA_USUARIO AS OFICINA,

--INSERTADO EN RF
IMEI, EQUIPO, ICC,
DOMAIN_LOGIN_OW, NOMBRE_USUARIO_OW,
DOMAIN_LOGIN_SUB, NOMBRE_USUARIO_SUB,
CAMPANIA, 	CODIGO_DISTRIBUIDOR_USUARIO AS CODIGO_DISTRIBUIDOR,
CODIGO_PLAZA_USUARIO AS CODIGO_PLAZA, NOM_PLAZA_USUARIO AS NOM_PLAZA, REGION_USUARIO AS REGION,
EJECUTIVO_ASIGNADO_PTR, AREA_PTR, 
CODIGO_VENDEDOR_DA_PTR, JEFATURA_PTR,
CODIGO_USUARIO,
CALF_RIESGO, CAP_ENDEU, VALOR_CRED,
ACCOUNT_NUM_ANTERIOR, CIUDAD_USUARIO, 
PROVINCIA_USUARIO, CAST( NULL AS STRING) AS MISMO_CLIENTE 
FROM db_cs_altas.otc_t_transfer_in_bi WHERE p_FECHA_PROCESO='${fecha_movimientos_cp}';

--ELIMINA LA DATA PRE EXISTENTE
DELETE FROM ${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST WHERE TIPO='POS_PRE' AND FECHA  BETWEEN '${f_inicio}' AND '${fecha_proceso}'  ;
	--IF EXISTS 
--INSERTA LA DATA DEL MES
INSERT INTO ${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST
SELECT 'POS_PRE' AS TIPO,
TELEFONO,
FECHA_TRANSFERENCIA AS FECHA, 
CANAL_USUARIO as CANAL,
SUB_CANAL, 
CAST( NULL AS STRING) AS NUEVO_SUB_CANAL,         
NOM_DISTRIBUIDOR_USUARIO AS DISTRIBUIDOR, 
OFICINA_USUARIO AS OFICINA,
--    								INSERTADO EN RF
IMEI, EQUIPO, ICC,
DOMAIN_LOGIN_OW, NOMBRE_USUARIO_OW,
DOMAIN_LOGIN_SUB, NOMBRE_USUARIO_SUB,
CAMPANIA_USUARIO AS CAMPANIA, CODIGO_DISTRIBUIDOR_USUARIO AS CODIGO_DISTRIBUIDOR,
CODIGO_PLAZA_USUARIO AS CODIGO_PLAZA, NOM_PLAZA_USUARIO AS NOM_PLAZA, REGION_USUARIO AS REGION,
EJECUTIVO_ASIGNADO_PTR, AREA_PTR, 
CODIGO_VENDEDOR_DA_PTR, JEFATURA_PTR,
CODIGO_USUARIO,
CAST( NULL AS STRING) AS CALF_RIESGO, CAST( NULL AS STRING) AS CAP_ENDEU, CAST( NULL AS STRING) AS VALOR_CRED,
ACCOUNT_NUM_ANTERIOR, CIUDAD_USUARIO, 
PROVINCIA_USUARIO, CAST( NULL AS STRING) AS MISMO_CLIENTE 
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
FROM db_cs_altas.otc_t_transfer_OUT_bi WHERE p_FECHA_PROCESO='${fecha_movimientos_cp}';

--ELIMINA LA DATA PRE EXISTENTE	
DELETE FROM ${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST WHERE FECHA BETWEEN '${f_inicio}' AND '${fecha_proceso}';
--INSERTA LA DATA DEL MES
INSERT INTO ${ESQUEMA_TABLA}.otc_t_cambio_plan_hist	
SELECT TIPO_MOVIMIENTO AS TIPO,
TELEFONO,
FECHA_CAMBIO_PLAN AS FECHA,
CANAL,
SUB_CANAL,
CAST( NULL AS STRING) AS NUEVO_SUB_CANAL, 
NOM_DISTRIBUIDOR AS DISTRIBUIDOR ,
OFICINA, 
CODIGO_PLAN_ANTERIOR AS COD_PLAN_ANTERIOR, 
DESCRIPCION_PLAN_ANTERIOR AS DES_PLAN_ANTERIOR, 
TARIFA_OV_PLAN_ANT AS  TB_DESCUENTO, 
DESCUENTO_TARIFA_PLAN_ANT AS TB_OVERRIDE, 
DELTA AS DELTA,
--INSERTADO EN RF
CODIGO_USUARIO_ORDEN AS DOMAIN_LOGIN_OW, NOMBRE_USUARIO_ORDEN AS NOMBRE_USUARIO_OW,
CODIGO_USUARIO_SUBMIT AS DOMAIN_LOGIN_SUB, NOMBRE_USUARIO_SUBMIT AS NOMBRE_USUARIO_SUB,
CAMPANIA, CAST( NULL AS STRING) AS CODIGO_DISTRIBUIDOR,
CAST( NULL AS STRING) AS CODIGO_PLAZA, CAST( NULL AS STRING) AS NOM_PLAZA, CAST( NULL AS STRING) AS REGION,
DESCRIPCION_PLAN_ANTERIOR AS NOMBRE_PLAN_ANTERIOR, TARIFA_BASICA_ANTERIOR,
FECHA_INICIO_PLAN_ANTERIOR,
TARIFA_FINAL_PLAN_ACT, TARIFA_FINAL_PLAN_ANT
-------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------

FROM db_cs_altas.otc_t_cambio_plan_bi WHERE p_FECHA_PROCESO=${fecha_movimientos_cp};

--OBTIENE EL ÛŒTIMO EVENTO DEL ALTA EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC;
CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC AS
SELECT
XX.TIPO , 
XX.TELEFONO,
XX.FECHA, 
XX.CANAL,
XX.SUB_CANAL, 
XX.NUEVO_SUB_CANAL,
XX.PORTABILIDAD, 
XX.Operadora_origen,
XX.Operadora_destino,
XX.motivo,		   
XX.DISTRIBUIDOR , 
XX.OFICINA,
--INSERTADO EN RF
XX.IMEI, XX.EQUIPO, XX.ICC,
XX.COD_CATEGORIA,
XX.DOMAIN_LOGIN_OW, XX.NOMBRE_USUARIO_OW,
XX.DOMAIN_LOGIN_SUB, XX.NOMBRE_USUARIO_SUB,
XX.COD_DA, XX.NOM_USUARIO,
XX.CAMPANIA, XX.CODIGO_DISTRIBUIDOR,
XX.CODIGO_PLAZA, XX.NOM_PLAZA, XX.REGION, 
XX.PROVINCIA_IVR,
XX.EJECUTIVO_ASIGNADO_PTR, XX.AREA_PTR, 
XX.CODIGO_VENDEDOR_DA_PTR, XX.JEFATURA_PTR,
XX.PROVINCIA_MS,
XX.CODIGO_USUARIO,
XX.CALF_RIESGO, XX.CAP_ENDEU, XX.VALOR_CRED
from
(
SELECT
AA.TIPO , 
AA.TELEFONO,
AA.FECHA, 
AA.CANAL,
AA.SUB_CANAL, 
AA.NUEVO_SUB_CANAL,
AA.PORTABILIDAD, 
AA.Operadora_origen,
AA.Operadora_destino,
AA.motivo,		   
AA.DISTRIBUIDOR , 
AA.OFICINA,
--INSERTADO EN RF
AA.IMEI, AA.EQUIPO, AA.ICC,
AA.COD_CATEGORIA,
AA.DOMAIN_LOGIN_OW, AA.NOMBRE_USUARIO_OW,
AA.DOMAIN_LOGIN_SUB, AA.NOMBRE_USUARIO_SUB,
AA.COD_DA, AA.NOM_USUARIO,
AA.CAMPANIA, AA.CODIGO_DISTRIBUIDOR,
AA.CODIGO_PLAZA, AA.NOM_PLAZA, AA.REGION, 
AA.PROVINCIA_IVR,
AA.EJECUTIVO_ASIGNADO_PTR, AA.AREA_PTR, 
AA.CODIGO_VENDEDOR_DA_PTR, AA.JEFATURA_PTR,
AA.PROVINCIA_MS,
AA.CODIGO_USUARIO,
AA.CALF_RIESGO, AA.CAP_ENDEU, AA.VALOR_CRED
, ROW_NUMBER() OVER (PARTITION BY aa.TIPO,aa.TELEFONO ORDER BY  aa.FECHA DESC) AS RNUM
FROM ${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST AS AA
WHERE FECHA <'${fecha_movimientos}'
AND TIPO='ALTA'
) XX
where XX.rnum = 1
;

--OBTIENE EL ÛŒTIMO EVENTO DE LAS BAJAS EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.OTC_T_BAJA_HIST_UNIC;
CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_BAJA_HIST_UNIC AS
SELECT
XX.TIPO , 
XX.TELEFONO,
XX.FECHA, 
XX.CANAL,
XX.SUB_CANAL, 
XX.NUEVO_SUB_CANAL,
XX.PORTABILIDAD, 
XX.Operadora_origen,
XX.Operadora_destino,
XX.motivo,		   
XX.DISTRIBUIDOR , 
XX.OFICINA,

--INSERTADO EN RF
XX.IMEI,XX.EQUIPO ,XX.ICC,
XX.COD_CATEGORIA,
XX.DOMAIN_LOGIN_OW, XX.NOMBRE_USUARIO_OW,
XX.DOMAIN_LOGIN_SUB, XX.NOMBRE_USUARIO_SUB,
XX.COD_DA, XX.NOM_USUARIO,
XX.CAMPANIA, XX.CODIGO_DISTRIBUIDOR,
XX.CODIGO_PLAZA, XX.NOM_PLAZA, XX.REGION, 
XX.PROVINCIA_IVR,
XX.EJECUTIVO_ASIGNADO_PTR, XX.AREA_PTR, 
XX.CODIGO_VENDEDOR_DA_PTR, XX.JEFATURA_PTR,
XX.PROVINCIA_MS,
XX.CODIGO_USUARIO,
XX.CALF_RIESGO, XX.CAP_ENDEU, XX.VALOR_CRED
---------------------------------------
from
(
SELECT
AA.TIPO , 
AA.TELEFONO,
AA.FECHA, 
AA.CANAL,
AA.SUB_CANAL, 
AA.NUEVO_SUB_CANAL,
AA.PORTABILIDAD, 
AA.Operadora_origen,
AA.Operadora_destino,
AA.motivo,		   
AA.DISTRIBUIDOR , 
AA.OFICINA,

--INSERTADO EN RF
AA.IMEI,AA.EQUIPO ,AA.ICC,
AA.COD_CATEGORIA,
AA.DOMAIN_LOGIN_OW, AA.NOMBRE_USUARIO_OW,
AA.DOMAIN_LOGIN_SUB, AA.NOMBRE_USUARIO_SUB,
AA.COD_DA, AA.NOM_USUARIO,
AA.CAMPANIA, AA.CODIGO_DISTRIBUIDOR,
AA.CODIGO_PLAZA, AA.NOM_PLAZA, AA.REGION, 
AA.PROVINCIA_IVR,
AA.EJECUTIVO_ASIGNADO_PTR, AA.AREA_PTR, 
AA.CODIGO_VENDEDOR_DA_PTR, AA.JEFATURA_PTR,
AA.PROVINCIA_MS,
AA.CODIGO_USUARIO,
AA.CALF_RIESGO, AA.CAP_ENDEU, AA.VALOR_CRED
---------------------------------------
, ROW_NUMBER() OVER (PARTITION BY aa.TIPO,aa.TELEFONO ORDER BY  aa.FECHA DESC) AS RNUM
FROM ${ESQUEMA_TABLA}.OTC_T_ALTA_BAJA_HIST AS AA
WHERE FECHA <'${fecha_movimientos}'
AND TIPO='BAJA'
) XX
where XX.rnum = 1
;

--OBTIENE EL ÛŒTIMO EVENTO DE LAS TRANSFERENCIAS OUT EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC;
CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC AS
select
XX.TIPO , 
XX.TELEFONO,
XX.FECHA, 
XX.CANAL,
XX.SUB_CANAL, 
XX.NUEVO_SUB_CANAL,
XX.DISTRIBUIDOR , 
XX.OFICINA,
--    								INSERTADO EN RF
XX.IMEI, XX.EQUIPO, XX.ICC,
XX.DOMAIN_LOGIN_OW, XX.NOMBRE_USUARIO_OW,
XX.DOMAIN_LOGIN_SUB, XX.NOMBRE_USUARIO_SUB,
XX.CAMPANIA, XX.CODIGO_DISTRIBUIDOR,
XX.CODIGO_PLAZA, XX.NOM_PLAZA,XX.REGION,
XX.EJECUTIVO_ASIGNADO_PTR, XX.AREA_PTR, 
XX.CODIGO_VENDEDOR_DA_PTR, XX.JEFATURA_PTR,
XX.CODIGO_USUARIO,
XX.CALF_RIESGO, XX.CAP_ENDEU, XX.VALOR_CRED,
XX.ACCOUNT_NUM_ANTERIOR, XX.CIUDAD_USUARIO, 
XX.PROVINCIA_USUARIO, XX.MISMO_CLIENTE 
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
from
(
SELECT
AA.TIPO , 
AA.TELEFONO,
AA.FECHA, 
AA.CANAL,
AA.SUB_CANAL, 
AA.NUEVO_SUB_CANAL,
AA.DISTRIBUIDOR , 
AA.OFICINA,
--					INSERTADO EN RF
AA.IMEI, AA.EQUIPO, AA.ICC,
AA.DOMAIN_LOGIN_OW, AA.NOMBRE_USUARIO_OW,
AA.DOMAIN_LOGIN_SUB, AA.NOMBRE_USUARIO_SUB,
AA.CAMPANIA, AA.CODIGO_DISTRIBUIDOR,
AA.CODIGO_PLAZA, AA.NOM_PLAZA,AA.REGION,
AA.EJECUTIVO_ASIGNADO_PTR, AA.AREA_PTR, 
AA.CODIGO_VENDEDOR_DA_PTR, AA.JEFATURA_PTR,
AA.CODIGO_USUARIO,
AA.CALF_RIESGO, AA.CAP_ENDEU, AA.VALOR_CRED,
AA.ACCOUNT_NUM_ANTERIOR, AA.CIUDAD_USUARIO, 
AA.PROVINCIA_USUARIO, AA.MISMO_CLIENTE 
--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
, ROW_NUMBER() OVER (PARTITION BY aa.TIPO,aa.TELEFONO ORDER BY  aa.FECHA DESC) AS RNUM
FROM ${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST AS AA
WHERE FECHA <'${fecha_movimientos}'
AND TIPO='POS_PRE'
) XX
where XX.rnum = 1
;

--OBTIENE EL ÛŒTIMO EVENTO DE LAS TRANSFERENCIAS IN  EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC;
CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC AS
select
XX.TIPO , 
XX.TELEFONO,
XX.FECHA, 
XX.CANAL,
XX.SUB_CANAL, 
XX.NUEVO_SUB_CANAL,
XX.DISTRIBUIDOR , 
XX.OFICINA,
--INSERTADO EN RF
XX.IMEI, XX.EQUIPO, XX.ICC,
XX.DOMAIN_LOGIN_OW, XX.NOMBRE_USUARIO_OW,
XX.DOMAIN_LOGIN_SUB, XX.NOMBRE_USUARIO_SUB,
XX.CAMPANIA, XX.CODIGO_DISTRIBUIDOR,
XX.CODIGO_PLAZA, XX.NOM_PLAZA, XX.REGION,
XX.EJECUTIVO_ASIGNADO_PTR, XX.AREA_PTR, 
XX.CODIGO_VENDEDOR_DA_PTR, XX.JEFATURA_PTR,
XX.CODIGO_USUARIO,
XX.CALF_RIESGO, XX.CAP_ENDEU, XX.VALOR_CRED,
XX.ACCOUNT_NUM_ANTERIOR, XX.CIUDAD_USUARIO, 
XX.PROVINCIA_USUARIO, XX.MISMO_CLIENTE
------XXXXXXXXXXXXXXXXXXXXXXXXXXXXX------------------
from
(
SELECT
AA.TIPO , 
AA.TELEFONO,
AA.FECHA, 
AA.CANAL,
AA.SUB_CANAL, 
AA.NUEVO_SUB_CANAL,
AA.DISTRIBUIDOR , 
AA.OFICINA,
--INSERTADO EN RF
AA.IMEI, AA.EQUIPO, AA.ICC,
AA.DOMAIN_LOGIN_OW, AA.NOMBRE_USUARIO_OW,
AA.DOMAIN_LOGIN_SUB, AA.NOMBRE_USUARIO_SUB,
AA.CAMPANIA, AA.CODIGO_DISTRIBUIDOR,
AA.CODIGO_PLAZA, AA.NOM_PLAZA, AA.REGION,
AA.EJECUTIVO_ASIGNADO_PTR, AA.AREA_PTR, 
AA.CODIGO_VENDEDOR_DA_PTR, AA.JEFATURA_PTR,
AA.CODIGO_USUARIO,
AA.CALF_RIESGO, AA.CAP_ENDEU, AA.VALOR_CRED,
AA.ACCOUNT_NUM_ANTERIOR, AA.CIUDAD_USUARIO, 
AA.PROVINCIA_USUARIO, AA.MISMO_CLIENTE
------AAAAAAAAAAAAAAAAAAAAAAAAAAAAX------------------
, ROW_NUMBER() OVER (PARTITION BY aa.TIPO,aa.TELEFONO ORDER BY  aa.FECHA DESC) AS RNUM
FROM ${ESQUEMA_TABLA}.OTC_T_TRANSFER_HIST AS AA
WHERE FECHA <'${fecha_movimientos}'
AND TIPO='PRE_POS'
) XX
where XX.rnum = 1
;


--OBTIENE EL ÛŒTIMO EVENTO NO_RECICLABLE  EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST_UNIC;
CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST_UNIC AS
select
XX.TIPO , 
XX.TELEFONO,
XX.FECHA_ALTA, 
XX.DOCUMENTO_CLIENTE_ACT,
XX.PLAN_CODIGO,
XX.FECHA_PROCESO,
XX.CANAL_COMERCIAL,
XX.CAMPANIA,
XX.CODIGO_DISTRIBUIDOR,
XX.DISTRIBUIDOR,
XX.CODIGO_PLAZA, 
XX.NOM_PLAZA, 
XX.REGION,
XX.MARCA,
XX.LINEA_NEGOCIO_BAJA,
XX.DOCUMENTO_CLIENTE_ANT,
XX.DIAS,
XX.FECHA_BAJA
------XXXXXXXXXXXXXXXXXXXXXXXXXXXXX------------------
from
(
SELECT
AA.TIPO, 
AA.TELEFONO,
AA.FECHA_ALTA, 
AA.DOCUMENTO_CLIENTE_ACT,
AA.PLAN_CODIGO,
AA.FECHA_PROCESO,
AA.CANAL_COMERCIAL,
AA.CAMPANIA,
AA.CODIGO_DISTRIBUIDOR,
AA.DISTRIBUIDOR,
AA.CODIGO_PLAZA, 
AA.NOM_PLAZA, 
AA.REGION,
AA.MARCA,
AA.LINEA_NEGOCIO_BAJA,
AA.DOCUMENTO_CLIENTE_ANT,
AA.DIAS,
AA.FECHA_BAJA
------AAAAAAAAAAAAAAAAAAAAAAAAAAAAX------------------
, ROW_NUMBER() OVER (PARTITION BY aa.TIPO,aa.TELEFONO ORDER BY  aa.FECHA_PROCESO DESC) AS RNUM
FROM ${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST AS AA
WHERE FECHA_PROCESO <'${fecha_movimientos}'
AND TIPO='NO_RECICLABLE'
) XX
where XX.rnum = 1
;


--OBTIENE EL ÛŒTIMO EVENTO DE LOS CAMBIOS DE PLAN EN TODA LA HISTORIA HASTA LA FECHA DE PROCESO
DROP TABLE ${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST_UNIC;
CREATE TABLE ${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST_UNIC AS
SELECT
XX.TIPO , 
XX.TELEFONO,
XX.FECHA, 
XX.CANAL,
XX.SUB_CANAL, 
XX.NUEVO_SUB_CANAL,
XX.DISTRIBUIDOR , 
XX.OFICINA,
XX.COD_PLAN_ANTERIOR, 
XX.DES_PLAN_ANTERIOR, 
XX.TB_DESCUENTO, 
XX.TB_OVERRIDE, 
XX.DELTA,
--INSERTADO EN RF
XX.DOMAIN_LOGIN_OW, XX.NOMBRE_USUARIO_OW,
XX.DOMAIN_LOGIN_SUB, XX.NOMBRE_USUARIO_SUB,
XX.CAMPANIA, XX.CODIGO_DISTRIBUIDOR,
XX.CODIGO_PLAZA, XX.NOM_PLAZA, XX.REGION,
XX.NOMBRE_PLAN_ANTERIOR, XX.TARIFA_BASICA_ANTERIOR,
XX.FECHA_INICIO_PLAN_ANTERIOR,
XX.TARIFA_FINAL_PLAN_ACT, XX.TARIFA_FINAL_PLAN_ANT
-------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------
from
(
SELECT
AA.TIPO , 
AA.TELEFONO,
AA.FECHA, 
AA.CANAL,
AA.SUB_CANAL, 
AA.NUEVO_SUB_CANAL,
AA.DISTRIBUIDOR , 
AA.OFICINA,
AA.COD_PLAN_ANTERIOR, 
AA.DES_PLAN_ANTERIOR, 
AA.TB_DESCUENTO, 
AA.TB_OVERRIDE, 
AA.DELTA,
--INSERTADO EN RF
AA.DOMAIN_LOGIN_OW, AA.NOMBRE_USUARIO_OW,
AA.DOMAIN_LOGIN_SUB, AA.NOMBRE_USUARIO_SUB,
AA.CAMPANIA, AA.CODIGO_DISTRIBUIDOR,
AA.CODIGO_PLAZA, AA.NOM_PLAZA, AA.REGION,
AA.NOMBRE_PLAN_ANTERIOR, AA.TARIFA_BASICA_ANTERIOR,
AA.FECHA_INICIO_PLAN_ANTERIOR,
AA.TARIFA_FINAL_PLAN_ACT, AA.TARIFA_FINAL_PLAN_ANT
-------------XXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------
, ROW_NUMBER() OVER (PARTITION BY aa.TELEFONO ORDER BY  aa.FECHA DESC) AS RNUM
FROM ${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST AS AA
WHERE FECHA <'${fecha_movimientos}'
) XX
where XX.rnum = 1;


--REALIZAMOS EL CRUCE CON CADA TABLA USANDO LA TABLA PIVOT (TABLA RESULTANTE DE PIVOT_PARQUE) 
--Y AGREANDO LOS CAMPOS DE CADA TABLA RENOMBRANDOLOS DE ACUERDO AL MOVIEMIENTO QUE CORRESPONDA.
--ESTA ES LA PRIMERA TABLA RESULTANTE QUE SERVIRA PARA ALIMENTAR LA ESTRUCTURA OTC_T_360_GENERAL.

DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_tmp_t_mov;
CREATE TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_tmp_t_mov AS 
SELECT
NUM_TELEFONICO,
CODIGO_PLAN,
FECHA_ALTA,
FECHA_LAST_STATUS,
ESTADO_ABONADO,
FECHA_PROCESO,
NUMERO_ABONADO,
LINEA_NEGOCIO,
ACCOUNT_NUM,
SUB_SEGMENTO,
TIPO_DOC_CLIENTE,
IDENTIFICACION_CLIENTE,
CLIENTE,
CUSTOMER_REF,
COUNTED_DAYS,
LINEA_NEGOCIO_HOMOLOGADO,
CATEGORIA_PLAN,
TARIFA,
NOMBRE_PLAN,
MARCA,
CICLO_FACT,
CORREO_CLIENTE_PR,
TELEFONO_CLIENTE_PR,
--IMEI, ---PREGUNTAR BYRON
ORDEN,
TIPO_MOVIMIENTO_MES,
FECHA_MOVIMIENTO_MES,
ES_PARQUE,
BANCO,
A.FECHA AS FECHA_ALTA_HISTORICA,
A.CANAL AS CANAL_ALTA,
A.SUB_CANAL AS SUB_CANAL_ALTA,
A.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_ALTA,
A.DISTRIBUIDOR AS DISTRIBUIDOR_ALTA,
A.OFICINA AS OFICINA_ALTA,
-----------------RF
--A.IMEI AS IMEI_ALTA, 
A.EQUIPO AS EQUIPO_ALTA, A.ICC AS ICC_ALTA,
A.COD_CATEGORIA,
A.DOMAIN_LOGIN_OW AS DOMAIN_LOGIN_OW_ALTA, A.NOMBRE_USUARIO_OW AS NOMBRE_USUARIO_OW_ALTA,
A.DOMAIN_LOGIN_SUB AS DOMAIN_LOGIN_SUB_ALTA, A.NOMBRE_USUARIO_SUB AS NOMBRE_USUARIO_SUB_ALTA,
A.COD_DA, A.NOM_USUARIO,
A.CAMPANIA AS CAMPANIA_ALTA, A.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_ALTA,
A.CODIGO_PLAZA AS CODIGO_PLAZA_ALTA, A.NOM_PLAZA AS NOM_PLAZA_ALTA, A.REGION AS REGION_ALTA, 
A.PROVINCIA_IVR,
A.EJECUTIVO_ASIGNADO_PTR AS EJECUTIVO_ASIGNADO_PTR_ALTA, A.AREA_PTR AS AREA_PTR_ALTA, 
A.CODIGO_VENDEDOR_DA_PTR AS CODIGO_VENDEDOR_DA_PTR_ALTA, A.JEFATURA_PTR AS JEFATURA_PTR_ALTA,
A.PROVINCIA_MS,
A.CODIGO_USUARIO AS CODIGO_USUARIO_ALTA,
A.CALF_RIESGO AS CALF_RIESGO_ALTA, A.CAP_ENDEU AS CAP_ENDEU_ALTA, A.VALOR_CRED AS VALOR_CRED_ALTA,
--------------------
PORTABILIDAD,
OPERADORA_ORIGEN,
OPERADORA_DESTINO,
MOTIVO,
C.FECHA AS FECHA_PRE_POS,
C.CANAL AS CANAL_PRE_POS,
C.SUB_CANAL AS SUB_CANAL_PRE_POS,
C.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_PRE_POS,
C.DISTRIBUIDOR AS DISTRIBUIDOR_PRE_POS,
C.OFICINA AS OFICINA_PRE_POS,
--INSERTADO EN RF
--C.IMEI AS IMEI_TI, 
C.EQUIPO AS EQUIPO_TI, C.ICC AS ICC_TI,
C.DOMAIN_LOGIN_OW AS DOMAIN_LOGIN_OW_TI, C.NOMBRE_USUARIO_OW AS NOMBRE_USUARIO_OW_TI,
C.DOMAIN_LOGIN_SUB AS DOMAIN_LOGIN_SUB_TI, C.NOMBRE_USUARIO_SUB AS NOMBRE_USUARIO_SUB_TI,
C.CAMPANIA AS CAMPANIA_TI, C.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_TI,
C.CODIGO_PLAZA AS CODIGO_PLAZA_TI, C.NOM_PLAZA AS NOM_PLAZA_TI, C.REGION AS REGION_TI,
C.EJECUTIVO_ASIGNADO_PTR AS EJECUTIVO_ASIGNADO_PTR_TI, C.AREA_PTR AS AREA_PTR_TI, 
C.CODIGO_VENDEDOR_DA_PTR AS CODIGO_VENDEDOR_DA_PTR_TI, C.JEFATURA_PTR AS JEFATURA_PTR_TI,
C.CODIGO_USUARIO AS CODIGO_USUARIO_TI,
C.CALF_RIESGO AS CALF_RIESGO_TI, C.CAP_ENDEU AS CAP_ENDEU_TI, C.VALOR_CRED AS VALOR_CRED_TI,
C.ACCOUNT_NUM_ANTERIOR AS ACCOUNT_NUM_ANTERIOR_TI, C.CIUDAD_USUARIO AS CIUDAD_USUARIO_TI, 
C.PROVINCIA_USUARIO AS PROVINCIA_USUARIO_TI, C.MISMO_CLIENTE AS MISMO_CLIENTE_TI,
--------------------------------------------

D.FECHA AS FECHA_POS_PRE,
D.CANAL AS CANAL_POS_PRE,
D.SUB_CANAL AS SUB_CANAL_POS_PRE,
D.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_POS_PRE,
D.DISTRIBUIDOR AS DISTRIBUIDOR_POS_PRE,
D.OFICINA AS OFICINA_POS_PRE,
--INSERTADO EN RF
--D.IMEI AS IMEI_TO, 
D.EQUIPO AS EQUIPO_TO, D.ICC AS ICC_TO,
D.DOMAIN_LOGIN_OW AS DOMAIN_LOGIN_OW_TO, D.NOMBRE_USUARIO_OW AS NOMBRE_USUARIO_OW_TO,
D.DOMAIN_LOGIN_SUB AS DOMAIN_LOGIN_SUB_TO, D.NOMBRE_USUARIO_SUB AS NOMBRE_USUARIO_SUB_TO,
D.CAMPANIA AS CAMPANIA_TO, D.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_TO,
D.CODIGO_PLAZA AS CODIGO_PLAZA_TO, D.NOM_PLAZA AS NOM_PLAZA_TO,D.REGION AS REGION_TO,
D.EJECUTIVO_ASIGNADO_PTR AS EJECUTIVO_ASIGNADO_PTR_TO, D.AREA_PTR AS AREA_PTR_TO, 
D.CODIGO_VENDEDOR_DA_PTR AS CODIGO_VENDEDOR_DA_PTR_TO, D.JEFATURA_PTR AS JEFATURA_PTR_TO,
D.CODIGO_USUARIO AS CODIGO_USUARIO_TO,
D.CALF_RIESGO AS CALF_RIESGO_TO, D.CAP_ENDEU AS CAP_ENDEU_TO, D.VALOR_CRED AS VALOR_CRED_TO,
D.ACCOUNT_NUM_ANTERIOR AS ACCOUNT_NUM_ANTERIOR_TO, D.CIUDAD_USUARIO AS CIUDAD_USUARIO_TO, 
D.PROVINCIA_USUARIO AS PROVINCIA_USUARIO_TO, D.MISMO_CLIENTE AS MISMO_CLIENTE_TO, 
--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


E.FECHA AS FECHA_CAMBIO_PLAN,
E.CANAL AS CANAL_CAMBIO_PLAN,
E.SUB_CANAL AS SUB_CANAL_CAMBIO_PLAN,
E.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_CAMBIO_PLAN,
E.DISTRIBUIDOR AS DISTRIBUIDOR_CAMBIO_PLAN,
E.OFICINA AS OFICINA_CAMBIO_PLAN,
--INSERTADO EN RF
E.DOMAIN_LOGIN_OW  AS DOMAIN_LOGIN_OW_CP, E.NOMBRE_USUARIO_OW  AS NOMBRE_USUARIO_OW_CP,
E.DOMAIN_LOGIN_SUB AS DOMAIN_LOGIN_SUB_CP, E.NOMBRE_USUARIO_SUB AS NOMBRE_USUARIO_SUB_CP,
E.CAMPANIA AS CAMPANIA_CP, E.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_CP,
E.CODIGO_PLAZA AS CODIGO_PLAZA_CP, E.NOM_PLAZA AS NOM_PLAZA_CP, E.REGION AS REGION_CP,
E.NOMBRE_PLAN_ANTERIOR, E.TARIFA_BASICA_ANTERIOR,
E.FECHA_INICIO_PLAN_ANTERIOR,
E.TARIFA_FINAL_PLAN_ACT, E.TARIFA_FINAL_PLAN_ANT,
-------------XXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------
COD_PLAN_ANTERIOR,
DES_PLAN_ANTERIOR,
TB_DESCUENTO,
TB_OVERRIDE,
DELTA
FROM db_temporales.${TABLA_PIVOTANTE} as Z --check! CAMBIO EN RF ${ESQUEMA_TEMP}POR db_temporales
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC AS A
ON (NUM_TELEFONICO=A.TELEFONO)
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC AS C
ON (NUM_TELEFONICO=C.TELEFONO)
AND (LINEA_NEGOCIO_HOMOLOGADO <>'PREPAGO')
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC AS D
ON (NUM_TELEFONICO=D.TELEFONO)
AND (LINEA_NEGOCIO_HOMOLOGADO='PREPAGO')
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST_UNIC AS E
ON (NUM_TELEFONICO=E.TELEFONO)
AND (LINEA_NEGOCIO_HOMOLOGADO <>'PREPAGO');


--CREAMOS TABLA TEMPORAL UNION PARA OBTENER ULTIMO MOVIMIENTO DEL MES POR NUM_TELEFONO
DROP TABLE ${ESQUEMA_TEMP}.OTC_T_360_PARQUE_1_MOV_MES_TMP;
CREATE TABLE ${ESQUEMA_TEMP}.OTC_T_360_PARQUE_1_MOV_MES_TMP AS 
SELECT
TIPO,
TELEFONO,
FECHA AS FECHA_MOVIMIENTO_MES,
CANAL AS CANAL_MOVIMIENTO_MES,
SUB_CANAL AS SUB_CANAL_MOVIMIENTO_MES,
NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_MOVIMIENTO_MES,
DISTRIBUIDOR AS DISTRIBUIDOR_MOVIMIENTO_MES,
OFICINA AS OFICINA_MOVIMIENTO_MES,
PORTABILIDAD AS PORTABILIDAD_MOVIMIENTO_MES,
OPERADORA_ORIGEN AS OPERADORA_ORIGEN_MOVIMIENTO_MES,
OPERADORA_DESTINO AS OPERADORA_DESTINO_MOVIMIENTO_MES,
MOTIVO AS MOTIVO_MOVIMIENTO_MES,
COD_PLAN_ANTERIOR AS COD_PLAN_ANTERIOR_MOVIMIENTO_MES,
DES_PLAN_ANTERIOR AS DES_PLAN_ANTERIOR_MOVIMIENTO_MES,
TB_DESCUENTO AS TB_DESCUENTO_MOVIMIENTO_MES,
TB_OVERRIDE AS TB_OVERRIDE_MOVIMIENTO_MES,
DELTA AS DELTA_MOVIMIENTO_MES 
FROM (
SELECT TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
PORTABILIDAD,
OPERADORA_ORIGEN,
OPERADORA_DESTINO,
MOTIVO,
COD_PLAN_ANTERIOR,
DES_PLAN_ANTERIOR,
TB_DESCUENTO,
TB_OVERRIDE,
DELTA,
ROW_NUMBER() OVER (PARTITION BY TELEFONO ORDER BY  FECHA DESC) AS RNUM
FROM (		
SELECT TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
CAST( NULL AS STRING) AS PORTABILIDAD,
CAST( NULL AS STRING) AS OPERADORA_ORIGEN,
CAST( NULL AS STRING) AS OPERADORA_DESTINO,
CAST( NULL AS STRING) AS MOTIVO,
COD_PLAN_ANTERIOR,
DES_PLAN_ANTERIOR,
TB_DESCUENTO,
TB_OVERRIDE,
DELTA
FROM ${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST_UNIC
WHERE FECHA  BETWEEN '${f_inicio}' AND '${fecha_proceso}' 
UNION ALL 
SELECT
TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
CAST( NULL AS STRING) AS PORTABILIDAD,
CAST( NULL AS STRING) AS OPERADORA_ORIGEN,
CAST( NULL AS STRING) AS OPERADORA_DESTINO,
CAST( NULL AS STRING) AS MOTIVO,
CAST( NULL AS STRING) AS COD_PLAN_ANTERIOR,
CAST( NULL AS STRING) AS DES_PLAN_ANTERIOR,
CAST( NULL AS DOUBLE) AS TB_DESCUENTO,
CAST( NULL AS DOUBLE) AS TB_OVERRIDE,
CAST( NULL AS DOUBLE) AS DELTA
FROM ${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC
WHERE FECHA  BETWEEN '${f_inicio}' AND '${fecha_proceso}' 
UNION ALL 
SELECT
TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
CAST( NULL AS STRING) AS PORTABILIDAD,
CAST( NULL AS STRING) AS OPERADORA_ORIGEN,
CAST( NULL AS STRING) AS OPERADORA_DESTINO,
CAST( NULL AS STRING) AS MOTIVO,
CAST( NULL AS STRING) AS COD_PLAN_ANTERIOR,
CAST( NULL AS STRING) AS DES_PLAN_ANTERIOR,
CAST( NULL AS DOUBLE) AS TB_DESCUENTO,
CAST( NULL AS DOUBLE) AS TB_OVERRIDE,
CAST( NULL AS DOUBLE) AS DELTA
FROM ${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC
WHERE FECHA  BETWEEN '${f_inicio}' AND '${fecha_proceso}' 
UNION ALL 
SELECT
TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
PORTABILIDAD,
OPERADORA_ORIGEN,
OPERADORA_DESTINO,
MOTIVO,
CAST( NULL AS STRING) AS COD_PLAN_ANTERIOR,
CAST( NULL AS STRING) AS DES_PLAN_ANTERIOR,
CAST( NULL AS DOUBLE) AS TB_DESCUENTO,
CAST( NULL AS DOUBLE) AS TB_OVERRIDE,
CAST( NULL AS DOUBLE) AS DELTA
FROM ${ESQUEMA_TABLA}.OTC_T_BAJA_HIST_UNIC
WHERE FECHA  BETWEEN '${f_inicio}' AND '${fecha_proceso}' 
UNION ALL 
SELECT
TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
PORTABILIDAD,
OPERADORA_ORIGEN,
OPERADORA_DESTINO,
MOTIVO,
CAST( NULL AS STRING) AS COD_PLAN_ANTERIOR,
CAST( NULL AS STRING) AS DES_PLAN_ANTERIOR,
CAST( NULL AS DOUBLE) AS TB_DESCUENTO,
CAST( NULL AS DOUBLE) AS TB_OVERRIDE,
CAST( NULL AS DOUBLE) AS DELTA
FROM ${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC
WHERE FECHA  BETWEEN '${f_inicio}' AND '${fecha_proceso}' 
) ZZ ) TT
WHERE RNUM=1;
	
DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_mov_seg_tmp;	
CREATE TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_mov_seg_tmp AS 
SELECT	TIPO AS ORIGEN_ALTA_SEGMENTO,
TELEFONO,
FECHA AS FECHA_ALTA_SEGMENTO,
CANAL AS CANAL_ALTA_SEGMENTO,
SUB_CANAL AS SUB_CANAL_ALTA_SEGMENTO,
NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_ALTA_SEGMENTO,
DISTRIBUIDOR AS DISTRIBUIDOR_ALTA_SEGMENTO,
OFICINA AS OFICINA_ALTA_SEGMENTO,
PORTABILIDAD AS PORTABILIDAD_ALTA_SEGMENTO,
OPERADORA_ORIGEN AS OPERADORA_ORIGEN_ALTA_SEGMENTO,
OPERADORA_DESTINO AS OPERADORA_DESTINO_ALTA_SEGMENTO,
MOTIVO AS MOTIVO_ALTA_SEGMENTO
FROM (
SELECT TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
PORTABILIDAD,
OPERADORA_ORIGEN,
OPERADORA_DESTINO,
MOTIVO,
ROW_NUMBER() OVER (PARTITION BY TELEFONO ORDER BY  FECHA DESC) AS RNUM
FROM (		
SELECT
TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
CAST( NULL AS STRING) AS PORTABILIDAD,
CAST( NULL AS STRING) AS OPERADORA_ORIGEN,
CAST( NULL AS STRING) AS OPERADORA_DESTINO,
CAST( NULL AS STRING) AS MOTIVO		
FROM ${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC
UNION ALL 
SELECT
TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
CAST( NULL AS STRING) AS PORTABILIDAD,
CAST( NULL AS STRING) AS OPERADORA_ORIGEN,
CAST( NULL AS STRING) AS OPERADORA_DESTINO,
CAST( NULL AS STRING) AS MOTIVO
FROM ${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC
UNION ALL 
SELECT
TIPO,
TELEFONO,
FECHA,
CANAL,
SUB_CANAL,
NUEVO_SUB_CANAL,
DISTRIBUIDOR,
OFICINA,
PORTABILIDAD,
OPERADORA_ORIGEN,
OPERADORA_DESTINO,
MOTIVO
FROM ${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC
) ZZ ) TT
WHERE RNUM=1;			

DROP TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_tmp_t_mov_mes;
CREATE TABLE ${ESQUEMA_TEMP}.otc_t_360_parque_1_tmp_t_mov_mes AS
SELECT
NUM_TELEFONICO,
CODIGO_PLAN,
FECHA_ALTA,
FECHA_LAST_STATUS,
ESTADO_ABONADO,
FECHA_PROCESO,
NUMERO_ABONADO,
LINEA_NEGOCIO,
ACCOUNT_NUM,
SUB_SEGMENTO,
TIPO_DOC_CLIENTE,
IDENTIFICACION_CLIENTE,
CLIENTE,
CUSTOMER_REF,
COUNTED_DAYS,
LINEA_NEGOCIO_HOMOLOGADO,
CATEGORIA_PLAN,
TARIFA,
NOMBRE_PLAN,
MARCA,
CICLO_FACT,
CORREO_CLIENTE_PR,
TELEFONO_CLIENTE_PR,
IMEI,
ORDEN,
TIPO_MOVIMIENTO_MES,
B.FECHA_MOVIMIENTO_MES,
ES_PARQUE,
BANCO,
CANAL_MOVIMIENTO_MES,
SUB_CANAL_MOVIMIENTO_MES,
NUEVO_SUB_CANAL_MOVIMIENTO_MES,
DISTRIBUIDOR_MOVIMIENTO_MES,
OFICINA_MOVIMIENTO_MES,
PORTABILIDAD_MOVIMIENTO_MES,
OPERADORA_ORIGEN_MOVIMIENTO_MES,
OPERADORA_DESTINO_MOVIMIENTO_MES,
MOTIVO_MOVIMIENTO_MES,
COD_PLAN_ANTERIOR_MOVIMIENTO_MES,
DES_PLAN_ANTERIOR_MOVIMIENTO_MES,
TB_DESCUENTO_MOVIMIENTO_MES,
TB_OVERRIDE_MOVIMIENTO_MES,
DELTA_MOVIMIENTO_MES
FROM db_temporales.${TABLA_PIVOTANTE} AS B --check! CAMBIADO EN RF PARA ETAPA DE DESARROLLO ${ESQUEMA_TEMP} POR db_temporales
LEFT JOIN  ${ESQUEMA_TEMP}.OTC_T_360_PARQUE_1_MOV_MES_TMP AS A
ON (NUM_TELEFONICO=A.TELEFONO)
AND B.FECHA_MOVIMIENTO_MES=A.FECHA_MOVIMIENTO_MES;

