DROP TABLE db_desarrollo2021.otc_t_360_parque_1_tmp_t_mov;
CREATE TABLE db_desarrollo2021.otc_t_360_parque_1_tmp_t_mov AS 
SELECT
NUM_TELEFONICO,
CODIGO_PLAN,
FECHA_ALTA,
FECHA_LAST_STATUS,
ESTADO_ABONADO,
FECHA_PROCESO,
NUMERO_ABONADO,
LINEA_NEGOCIO,
ACCOUNT_NUM,
SUB_SEGMENTO,
TIPO_DOC_CLIENTE,
IDENTIFICACION_CLIENTE,
CLIENTE,
CUSTOMER_REF,
COUNTED_DAYS,
LINEA_NEGOCIO_HOMOLOGADO,
CATEGORIA_PLAN,
TARIFA,
NOMBRE_PLAN,
MARCA,
CICLO_FACT,
CORREO_CLIENTE_PR,
TELEFONO_CLIENTE_PR,
--IMEI, ---PREGUNTAR BYRON
ORDEN,
TIPO_MOVIMIENTO_MES,
FECHA_MOVIMIENTO_MES,
ES_PARQUE,
BANCO,
A.FECHA AS FECHA_ALTA_HISTORICA,
A.CANAL AS CANAL_ALTA,
A.SUB_CANAL AS SUB_CANAL_ALTA,
A.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_ALTA,
A.DISTRIBUIDOR AS DISTRIBUIDOR_ALTA,
A.OFICINA AS OFICINA_ALTA,
-----------------RF
A.IMEI AS IMEI_ALTA, A.EQUIPO AS EQUIPO_ALTA, A.ICC AS ICC_ALTA,
A.COD_CATEGORIA,
A.DOMAIN_LOGIN_OW AS DOMAIN_LOGIN_OW_ALTA, A.NOMBRE_USUARIO_OW AS NOMBRE_USUARIO_OW_ALTA,
A.DOMAIN_LOGIN_SUB AS DOMAIN_LOGIN_SUB_ALTA, A.NOMBRE_USUARIO_SUB AS NOMBRE_USUARIO_SUB_ALTA,
A.COD_DA, A.NOM_USUARIO,
A.CAMPANIA AS CAMPANIA_ALTA, A.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_ALTA,
A.CODIGO_PLAZA AS CODIGO_PLAZA_ALTA, A.NOM_PLAZA AS NOM_PLAZA_ALTA, A.REGION AS REGION_ALTA, 
A.PROVINCIA_IVR,
A.EJECUTIVO_ASIGNADO_PTR AS EJECUTIVO_ASIGNADO_PTR_ALTA, A.AREA_PTR AS AREA_PTR_ALTA, 
A.CODIGO_VENDEDOR_DA_PTR AS CODIGO_VENDEDOR_DA_PTR_ALTA, A.JEFATURA_PTR AS JEFATURA_PTR_ALTA,
A.PROVINCIA_MS,
A.CODIGO_USUARIO AS CODIGO_USUARIO_ALTA,
A.CALF_RIESGO AS CALF_RIESGO_ALTA, A.CAP_ENDEU AS CAP_ENDEU_ALTA, A.VALOR_CRED AS VALOR_CRED_ALTA,
--------------------
PORTABILIDAD,
OPERADORA_ORIGEN,
OPERADORA_DESTINO,
MOTIVO,
------------------------------------

C.FECHA AS FECHA_PRE_POS,
C.CANAL AS CANAL_PRE_POS,
C.SUB_CANAL AS SUB_CANAL_PRE_POS,
C.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_PRE_POS,
C.DISTRIBUIDOR AS DISTRIBUIDOR_PRE_POS,
C.OFICINA AS OFICINA_PRE_POS,
--INSERTADO EN RF
C.IMEI AS IMEI_TI, 
C.EQUIPO AS EQUIPO_TI, C.ICC AS ICC_TI,
C.DOMAIN_LOGIN_OW AS DOMAIN_LOGIN_OW_TI, C.NOMBRE_USUARIO_OW AS NOMBRE_USUARIO_OW_TI,
C.DOMAIN_LOGIN_SUB AS DOMAIN_LOGIN_SUB_TI, C.NOMBRE_USUARIO_SUB AS NOMBRE_USUARIO_SUB_TI,
C.CAMPANIA AS CAMPANIA_TI, C.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_TI,
C.CODIGO_PLAZA AS CODIGO_PLAZA_TI, C.NOM_PLAZA AS NOM_PLAZA_TI, C.REGION AS REGION_TI,
C.EJECUTIVO_ASIGNADO_PTR AS EJECUTIVO_ASIGNADO_PTR_TI, C.AREA_PTR AS AREA_PTR_TI, 
C.CODIGO_VENDEDOR_DA_PTR AS CODIGO_VENDEDOR_DA_PTR_TI, C.JEFATURA_PTR AS JEFATURA_PTR_TI,
C.CODIGO_USUARIO AS CODIGO_USUARIO_TI,
C.CALF_RIESGO AS CALF_RIESGO_TI, C.CAP_ENDEU AS CAP_ENDEU_TI, C.VALOR_CRED AS VALOR_CRED_TI,
C.ACCOUNT_NUM_ANTERIOR AS ACCOUNT_NUM_ANTERIOR_TI, C.CIUDAD_USUARIO AS CIUDAD_USUARIO_TI, 
C.PROVINCIA_USUARIO AS PROVINCIA_USUARIO_TI, C.MISMO_CLIENTE AS MISMO_CLIENTE_TI,
--------------------------------------------

D.FECHA AS FECHA_POS_PRE,
D.CANAL AS CANAL_POS_PRE,
D.SUB_CANAL AS SUB_CANAL_POS_PRE,
D.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_POS_PRE,
D.DISTRIBUIDOR AS DISTRIBUIDOR_POS_PRE,
D.OFICINA AS OFICINA_POS_PRE,
--INSERTADO EN RF
D.IMEI AS IMEI_TO, 
D.EQUIPO AS EQUIPO_TO, D.ICC AS ICC_TO,
D.DOMAIN_LOGIN_OW AS DOMAIN_LOGIN_OW_TO, D.NOMBRE_USUARIO_OW AS NOMBRE_USUARIO_OW_TO,
D.DOMAIN_LOGIN_SUB AS DOMAIN_LOGIN_SUB_TO, D.NOMBRE_USUARIO_SUB AS NOMBRE_USUARIO_SUB_TO,
D.CAMPANIA AS CAMPANIA_TO, D.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_TO,
D.CODIGO_PLAZA AS CODIGO_PLAZA_TO, D.NOM_PLAZA AS NOM_PLAZA_TO,D.REGION AS REGION_TO,
D.EJECUTIVO_ASIGNADO_PTR AS EJECUTIVO_ASIGNADO_PTR_TO, D.AREA_PTR AS AREA_PTR_TO, 
D.CODIGO_VENDEDOR_DA_PTR AS CODIGO_VENDEDOR_DA_PTR_TO, D.JEFATURA_PTR AS JEFATURA_PTR_TO,
D.CODIGO_USUARIO AS CODIGO_USUARIO_TO,
D.CALF_RIESGO AS CALF_RIESGO_TO, D.CAP_ENDEU AS CAP_ENDEU_TO, D.VALOR_CRED AS VALOR_CRED_TO,
D.ACCOUNT_NUM_ANTERIOR AS ACCOUNT_NUM_ANTERIOR_TO, D.CIUDAD_USUARIO AS CIUDAD_USUARIO_TO, 
D.PROVINCIA_USUARIO AS PROVINCIA_USUARIO_TO, D.MISMO_CLIENTE AS MISMO_CLIENTE_TO, 
--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
----------------XXXXXXXXXXXXXXXX  DESDE NO RECICLABLE
B.CANAL_COMERCIAL AS CANAL_COMERCIAL_NR,
B.CAMPANIA AS CAMPANIA_NR,
B.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_NR,
B.DISTRIBUIDOR AS DISTRIBUIDOR_NR,
B.CODIGO_PLAZA AS CODIGO_PLAZA_NR, 
B.NOM_PLAZA AS NOM_PLAZA_NR, 
B.REGION AS REGION_NR,
----------XXXXXXXXXXXXX
-- LOS CAMPOS ENTRE XXXXXXX SE OBTIENEN CRUZANDO CON EL CAT DE USUARIOS
B.LINEA_NEGOCIO_BAJA,
B.DOCUMENTO_CLIENTE_ANT,
B.DIAS,
B.FECHA_BAJA,
------------------------------------

E.FECHA AS FECHA_CAMBIO_PLAN,
E.CANAL AS CANAL_CAMBIO_PLAN,
E.SUB_CANAL AS SUB_CANAL_CAMBIO_PLAN,
E.NUEVO_SUB_CANAL AS NUEVO_SUB_CANAL_CAMBIO_PLAN,
E.DISTRIBUIDOR AS DISTRIBUIDOR_CAMBIO_PLAN,
E.OFICINA AS OFICINA_CAMBIO_PLAN,
--INSERTADO EN RF
E.DOMAIN_LOGIN_OW  AS DOMAIN_LOGIN_OW_CP, E.NOMBRE_USUARIO_OW  AS NOMBRE_USUARIO_OW_CP,
E.DOMAIN_LOGIN_SUB AS DOMAIN_LOGIN_SUB_CP, E.NOMBRE_USUARIO_SUB AS NOMBRE_USUARIO_SUB_CP,
E.CAMPANIA AS CAMPANIA_CP, E.CODIGO_DISTRIBUIDOR AS CODIGO_DISTRIBUIDOR_CP,
E.CODIGO_PLAZA AS CODIGO_PLAZA_CP, E.NOM_PLAZA AS NOM_PLAZA_CP, E.REGION AS REGION_CP,
E.NOMBRE_PLAN_ANTERIOR, E.TARIFA_BASICA_ANTERIOR,
E.FECHA_INICIO_PLAN_ANTERIOR,
E.TARIFA_FINAL_PLAN_ACT, E.TARIFA_FINAL_PLAN_ANT,
-------------XXXXXXXXXXXXXXXXXXXXXXXXXXX-------------------------------------
COD_PLAN_ANTERIOR,
DES_PLAN_ANTERIOR,
TB_DESCUENTO,
TB_OVERRIDE,
DELTA
FROM db_temporales.${TABLA_PIVOTANTE} as Z --check! CAMBIO EN RF db_desarrollo2021POR db_temporales
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_ALTA_HIST_UNIC AS A
ON (NUM_TELEFONICO=A.TELEFONO)
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_PRE_POS_HIST_UNIC AS C
ON (NUM_TELEFONICO=C.TELEFONO)
AND (LINEA_NEGOCIO_HOMOLOGADO <>'PREPAGO')
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_POS_PRE_HIST_UNIC AS D
ON (NUM_TELEFONICO=D.TELEFONO)
AND (LINEA_NEGOCIO_HOMOLOGADO='PREPAGO')
--insertado en RF
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_NO_RECICLABLE_HIST_UNIC AS B
ON (NUM_TELEFONICO=B.TELEFONO)
-----------------------------------------------------
LEFT JOIN  ${ESQUEMA_TABLA}.OTC_T_CAMBIO_PLAN_HIST_UNIC AS E
ON (NUM_TELEFONICO=E.TELEFONO)
AND (LINEA_NEGOCIO_HOMOLOGADO <>'PREPAGO');


